# Generated by Django 2.0.7 on 2018-11-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trade',
            fields=[
                ('ticker', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Max 2 decimal places', max_digits=20)),
                ('currency', models.CharField(help_text='3 letter currency code', max_length=3)),
                ('quantity', models.IntegerField(default=0, help_text='Integer value')),
                ('timestamp', models.DateTimeField(help_text='Enter purchase details"')),
            ],
        ),
    ]
