# Generated by Django 2.0.7 on 2018-12-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('ticker', models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='Ticker')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Price')),
                ('currency', models.CharField(help_text='3 letter currency code', max_length=3, verbose_name='Currency')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('timestamp', models.DateTimeField(help_text='Enter purchase date and time"', verbose_name='TimeStamp')),
                ('action', models.CharField(default='Buy', help_text='"Buy" or "Sell"', max_length=4, verbose_name='Action')),
            ],
        ),
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('ticker', models.CharField(max_length=7)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('currency', models.CharField(help_text='3 letter currency code', max_length=3)),
                ('quantity', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(help_text='Enter purchase details"')),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('action', models.CharField(default='Buy', help_text='"Buy" or "Sell"', max_length=4, verbose_name='Action')),
            ],
        ),
    ]
