# Generated by Django 2.0.7 on 2018-11-22 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='trade',
            new_name='Portfolio',
        ),
    ]
