# Generated by Django 2.0.7 on 2018-11-23 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20181122_1856'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='Trade',
        ),
    ]
