# Generated by Django 2.0.7 on 2018-12-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20181217_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='action',
            field=models.CharField(choices=[('buy', 'BUY'), ('sell', 'SELL')], help_text='"Buy" or "Sell"', max_length=4, verbose_name='Action'),
        ),
    ]
