# Generated by Django 2.0.7 on 2018-12-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20181123_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('ticker', models.CharField(max_length=7)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Max 2 decimal places', max_digits=20)),
                ('currency', models.CharField(help_text='3 letter currency code', max_length=3)),
                ('quantity', models.IntegerField(default=0, help_text='Integer value')),
                ('timestamp', models.DateTimeField(help_text='Enter purchase details"')),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='trade',
            name='currency',
            field=models.CharField(help_text='3 letter currency code', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Max 2 decimal places', max_digits=20, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Integer value', verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='ticker',
            field=models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='Ticker'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='timestamp',
            field=models.DateTimeField(help_text='Enter purchase date and time"', verbose_name='TimeStamp'),
        ),
    ]
