# Generated by Django 2.0.7 on 2018-12-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20181219_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='action',
            field=models.CharField(blank=True, choices=[('', 'Action'), ('buy', 'BUY'), ('sell', 'SELL')], help_text='"Buy" or "Sell"', max_length=4, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='currency',
            field=models.CharField(blank=True, help_text='3 letter currency code', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='quantity',
            field=models.IntegerField(blank=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='ticker',
            field=models.CharField(blank=True, max_length=7, primary_key=True, serialize=False, verbose_name='Ticker'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='timestamp',
            field=models.DateTimeField(blank=True, help_text='Enter purchase date and time"', verbose_name='TimeStamp'),
        ),
    ]
