# Generated by Django 2.0.7 on 2018-12-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20181219_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='action',
            field=models.CharField(blank=True, choices=[('', 'Action'), ('buy', 'BUY'), ('sell', 'SELL')], help_text='"BUY" or "SELL"', max_length=4, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='tradehistory',
            name='action',
            field=models.CharField(max_length=4, verbose_name='Action'),
        ),
    ]
