# Generated by Django 2.0.7 on 2019-01-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20181219_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='currency',
            field=models.CharField(blank=True, choices=[('', 'Currency'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('USD', 'USD')], help_text='3 letter currency code', max_length=3, verbose_name='Currency'),
        ),
    ]
