# Generated by Django 2.0.7 on 2019-01-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20190102_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashAccounts',
            fields=[
                ('account', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False, verbose_name='Account Name')),
                ('broker', models.CharField(blank=True, max_length=20, verbose_name='Broker')),
                ('ccy', models.CharField(blank=True, choices=[('', 'Currency'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('USD', 'USD')], max_length=3, verbose_name='Currency Account')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=20, verbose_name='Balance')),
            ],
        ),
        migrations.AddField(
            model_name='trade',
            name='broker',
            field=models.CharField(blank=True, max_length=20, verbose_name='Broker Account'),
        ),
        migrations.AddField(
            model_name='tradehistory',
            name='broker',
            field=models.CharField(blank=True, max_length=20, verbose_name='Broker Account'),
        ),
    ]
