# Generated by Django 2.0.7 on 2019-01-22 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20190122_1919'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CashAccounts',
            new_name='Accounts',
        ),
    ]
