# Generated by Django 2.0.7 on 2019-01-23 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20190122_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradehistory',
            old_name='fxCharge',
            new_name='fee',
        ),
        migrations.RemoveField(
            model_name='tradehistory',
            name='transactionFee',
        ),
    ]
