# Generated by Django 2.0.7 on 2019-01-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20190123_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='account',
            field=models.CharField(blank=True, choices=[('', 'Broker Account')], max_length=20, verbose_name='Broker Account'),
        ),
    ]
