# Generated by Django 2.0.7 on 2019-01-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20190124_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='account',
            field=models.CharField(blank=True, max_length=20, verbose_name='Broker Account'),
        ),
    ]
