# Generated by Django 2.0.7 on 2019-01-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20190124_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='industry',
            field=models.CharField(blank=True, max_length=50, verbose_name='Industry'),
        ),
        migrations.AddField(
            model_name='trade',
            name='instrument',
            field=models.CharField(blank=True, max_length=50, verbose_name='Instrument'),
        ),
        migrations.AddField(
            model_name='trade',
            name='long_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Long Name'),
        ),
        migrations.AddField(
            model_name='trade',
            name='sector',
            field=models.CharField(blank=True, max_length=50, verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='tradehistory',
            name='industry',
            field=models.CharField(blank=True, max_length=50, verbose_name='Industry'),
        ),
        migrations.AddField(
            model_name='tradehistory',
            name='instrument',
            field=models.CharField(blank=True, max_length=50, verbose_name='Instrument'),
        ),
        migrations.AddField(
            model_name='tradehistory',
            name='long_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Long Name'),
        ),
        migrations.AddField(
            model_name='tradehistory',
            name='sector',
            field=models.CharField(blank=True, max_length=50, verbose_name='Sector'),
        ),
    ]
